development:
  adapter: postgresql
  encoding: unicode
  database: campagin
  pool: 5
  username: manjums
  password: manjums

test:
  adapter: postgresql
  encoding: unicode
  database: campagin
  pool: 5
  username: manjums
  password: manjums